version: "3.8"

services:
  data-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../data:/app/data
    command: ["python", "data_crawler.py"]