x-common:
  &common-config
  image: vnstock:1.2
  env_file:
    - .env
  environment:
    - IS_TEST=${IS_TEST}
    - GCS_CREDENTIALS=${GCS_CREDENTIALS}
    - GCS_BUCKET=${GCS_BUCKET}
  volumes:
    - ./gcs_credentials.json:/app/gcs_credentials.json:ro

services:
  company:
    <<: *common-config
    command: [ "python", "src/data_crawler/companies.py" ]

  financial-data:
    <<: *common-config
    command: [ "python", "src/data_crawler/financial_data.py" ]

  company-info:
    <<: *common-config
    command: [ "python", "src/data_crawler/company_info.py" ]

  company-officer:
    <<: *common-config
    command: [ "python", "src/data_crawler/officers.py" ]

  company-shareholder:
    <<: *common-config
    command: [ "python", "src/data_crawler/shareholders.py" ]

  company-dividends:
    <<: *common-config
    command: [ "python", "src/data_crawler/dividends.py" ]

  company-stock-quote:
    <<: *common-config
    command: [ "python", "src/data_crawler/stock_quote.py" ]
