version: "3.8"

x-common:
  &common-config
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    - IS_TEST=${IS_TEST}
    - GCS_CREDENTIALS=${GCS_CREDENTIALS}
    - GCS_BUCKET=${GCS_BUCKET}
  volumes:
    - ./gcs_credentials.json:/app/gcs_credentials.json:ro

services:
  company:
    <<: *common-config
    command: [ "python", "src/companies.py" ]

  financial-data:
    <<: *common-config
    command: [ "python", "src/financial_data.py" ]

  company-info:
    <<: *common-config
    command: [ "python", "src/company_info.py" ]

  company-officer:
    <<: *common-config
    command: [ "python", "src/officers.py" ]

  company-shareholder:
    <<: *common-config
    command: [ "python", "src/shareholders.py" ]

  company-dividends:
    <<: *common-config
    command: [ "python", "src/dividends.py" ]

  company-stock-quote:
    <<: *common-config
    command: [ "python", "src/stock_quote.py" ]

volumes:
  vnstock: