version: "3.8"

services:
  company:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/companies.py" ]

  financial-data:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/financial_data.py" ]

  company-info:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/company_info.py" ]

  company-officer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/officers.py" ]

  company-shareholder:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/shareholders.py" ]

  company-dividends:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/dividends.py" ]

  company-stock-quote:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - IS_TEST=${IS_TEST}
    volumes:
      - vnstock:/app/data
      - vnstock:/app/logs
    command: [ "python", "src/stock_quote.py" ]


volumes:
  vnstock: